@baseUrl = http://localhost:3333



# @name healthCheck
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

#Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
"name": "teste de sala",
"description": "teste de uma sala"
}

###
@roomId = {{createRoom.response.body.$.roomId}}
###

#Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/40c66a6b-73ed-4331-bb01-cdfd551aebe8/questions

###

#Create room questions
# @name createRoomQuestions
POST {{baseUrl}}/rooms/40c66a6b-73ed-4331-bb01-cdfd551aebe8/questions
Content-Type: application/json

{
"question": "o que é gato"
}



